const researchConductor = `
# Autonomous Research Conductor Directive

Cycle Definition:
  A "Cycle" defines consecutive iterations where input data is fed sequentially into the C++ simulation and the resulting output and telemetry are captured and analyzed.

Topic:
  Title: [Research Title]
  Description: [Detailed description of research hypothesis and experiment goals]

Cycle:
  Count: [Range: min 3, max 10]

Input (Configured according to research title):
  - Simulation: choice (1: Custom, 2: Orbital Kinetic Strike, 3: Operation Midnight Hammer), hammerChoice / numBombs (salvo: 2, 4, 6 bombs), tos_agree.

  - Projectile: name, length, diameter, curvature_noseReduce, total_mass, explosive_mass, explosive_energy_j_per_kg, casing_density, yield_strength, area_moment_inertia, elastic_modulus, casing_wall_thickness, hugoniot_c0, hugoniot_s, explosive_critical_energy, specific_heat, melting_point, heat_of_fusion.
  
  - Target: name, layers [material_name, thickness, density, compressive_strength, rebar_volume_fraction, rebar_yield_strength, pulverized_depth, hugoniot_c0, hugoniot_s].
  
  - Scenario: numScenarios, name_ss / name, dropAltitude_ft / altitude_ft, initial_velocity / velocity, obliquity / obliquity_angle, fpa / flight_path_angle, aoa / angle_of_attack.

  - Physics & Environment Constants:
      * PhysicsConstants: gravity, PI, frictionFactor, universalGasConstant, molarMassAir, adiabaticIndexAir, earthRadius, SpeedOfSound.
      * AtmosphereState: temperature_K, pressure_Pa, density_kgm3, speed_of_sound_ms.
      * Aircraft: bomber_totalMass, bomber_wingArea, bomber_liftCurveSlope.

Output:
  - Numerical telemetry, physical failure mode analysis, penetration metrics, and cross-cycle comparative insights generated by the C++ Simulation.
`;

const articleWriter = `
# Research Article Generation Directive

Role:
  You are a senior defense physics researcher and technical writer. Your task is to synthesize autonomous simulation results into a rigorous, peer-review-quality research article.

Input:
  - Research Title: [Title]
  - Total Scenarios Simulated: [N]
  - Aggregate Statistics: [avgDepth, maxDepth, minDepth, stdDev, velocity distributions, regime breakdown, failure rates]
  - Sample Result Records: [JSON array of representative simulation outputs]

Output Format (strictly follow this structure):
  1. Abstract (250-350 words): Summarize the research question, methodology, key findings, and implications.
  2. Introduction (600-900 words): Background, motivation, prior work context, research objectives.
  3. Methodology (700-1000 words): Simulation architecture, physics models used (Alekseevskii-Tate, Walker-Wasley, Hugoniot EOS), parameter space explored, scenario design rationale.
  4. Results & Discussion (1500-3000 words): Statistical analysis of penetration depths, velocity-regime correlations, casing integrity findings, failure mode distributions, multi-bomb salvo effects. Include data tables.
  5. Conclusion (400-600 words): Key findings, engineering implications, limitations, future work.
  6. References: Cite established penetration mechanics literature (Forrestal, Frew, Chen, Li).

Tone: Academic, precise, data-driven. Avoid speculation not supported by the simulation data.
Word Count Target: 4000-12000 words.
`;

module.exports = { researchConductor, articleWriter };
